"""make card columns nullable

Revision ID: 09d32deb4d4e
Revises: 409e91b399fb
Create Date: 2021-01-05 00:36:22.334915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09d32deb4d4e'
down_revision = '409e91b399fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'mana_cost',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('cards', 'oracle_text',
               existing_type=sa.TEXT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cards', 'oracle_text',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('cards', 'mana_cost',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
