"""add_image_uri_to_cards

Revision ID: 155199534481
Revises: 09d32deb4d4e
Create Date: 2021-07-07 22:25:31.689605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155199534481'
down_revision = '09d32deb4d4e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cards', sa.Column('image_uri', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cards', 'image_uri')
    # ### end Alembic commands ###
