"""create decks table

Revision ID: 299f30f5561a
Revises: 
Create Date: 2020-11-24 21:23:47.169068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299f30f5561a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('decks')
    # ### end Alembic commands ###
