"""add deck_cards

Revision ID: 409e91b399fb
Revises: e516586ec4b3
Create Date: 2020-12-28 21:52:11.936485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409e91b399fb'
down_revision = 'e516586ec4b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('deck_cards',
    sa.Column('deck_id', sa.Integer(), nullable=False),
    sa.Column('card_oracle_id', sa.String(length=128), nullable=False),
    sa.Column('qty_main', sa.Integer(), server_default='0', nullable=False),
    sa.Column('qty_sideboard', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_commander', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_companion', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['card_oracle_id'], ['cards.oracle_id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.PrimaryKeyConstraint('deck_id', 'card_oracle_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deck_cards')
    # ### end Alembic commands ###
