"""add format to decks

Revision ID: 4d949bd91c49
Revises: 299f30f5561a
Create Date: 2020-11-26 00:33:53.779921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d949bd91c49'
down_revision = '299f30f5561a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('format', sa.String(length=128), nullable=False, server_default='standard'))
    op.alter_column('decks', 'format', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'format')
    # ### end Alembic commands ###
