"""add timestamps

Revision ID: d06ab00ac929
Revises: 4d949bd91c49
Create Date: 2020-12-07 00:29:37.962187

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd06ab00ac929'
down_revision = '4d949bd91c49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('decks', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('decks', sa.Column('updated_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.alter_column('decks', 'created_at', server_default=None)
    op.alter_column('decks', 'updated_at', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('decks', 'updated_at')
    op.drop_column('decks', 'created_at')
    # ### end Alembic commands ###
