"""create cards table

Revision ID: e516586ec4b3
Revises: d06ab00ac929
Create Date: 2020-12-21 23:30:03.325219

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e516586ec4b3'
down_revision = 'd06ab00ac929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cards',
    sa.Column('scryfall_id', sa.String(length=128), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('mana_cost', sa.Text(), nullable=False),
    sa.Column('cmc', sa.Float(), nullable=False),
    sa.Column('type_line', sa.Text(), nullable=False),
    sa.Column('oracle_text', sa.Text(), nullable=False),
    sa.Column('power', sa.String(length=128), nullable=True),
    sa.Column('toughness', sa.String(length=128), nullable=True),
    sa.Column('colors', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('color_identity', sa.JSON(), server_default='[]', nullable=False),
    sa.Column('legalities', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('scryfall_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cards')
    # ### end Alembic commands ###
